language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - pylint --ignore=tests santorini
  - pycodestyle --max-line-length=100 santorini
  - py.test santorini/tests/*